export default async (): Promise<string> => {
  return 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXNzaW9uIjoiaEVqTEtuckZPQmNSWWxGMTV2enE0QnE4Z3RLaUFqNWxpVXR0SnBmNmpKWkJJbFMwT0dKaWVZMHFPV3JseWRCWSIsInBhcnRpY2lwYW50X2lkIjoxOTU4LCJlc3RhYmxpc2htZW50X2lkIjo3MjAsInJvbGVfaWQiOjE2LCJ1c2VyX2lkIjpudWxsfQ.vsHPUGJr8TfB-NYzHFTbb5FRRT_WX4yby11x0ck2nnI';
};
