image: node:12

pipelines:
  default:
    - step:
        size: 2x
        caches:
          - node
        script: 
          - yarn
          - yarn test
          - yarn build
        services:
          - docker
