image: node:12

definitions:
  services:
    docker:
      memory: 3072

pipelines:
  default:
    - step:
        caches:
          - node
        script: 
          - yarn
          - yarn test
          - yarn build
        services:
          - docker
