export default {
  campaign: '/campanhas',
  campaignManagement: '/gerenciamento-de-campanhas',
  campaignCounting: '/apuracao-de-campanhas',
  contact: '/fale-conosco',
  extract: {
    my: '/myextract',
    channel: '/extrato-canal',
  },
  faq: '/faq',
  gallery: '/bibliotecas-juntos',
  goal: '/performance',
  home: '/home',
  howParticipate: '/como-participar',
  news: '/noticias',
  participantsIndication: '/indicacao-de-participantes',
  participantSimulation: '/visao-do-participante',
  pointManagement: '/distribuicao-de-pontos',
  products: '/solucoes',
  producer: '/indicar-produtor',
  profile: '/editar-perfil',
  regulation: '/regulamentos-e-termos',
  showcase: '/catalogo-de-premios',
  catalogoPi: '/catalogo',
  training: '/treinamentos',
  cockpit: '/cockpit',
  report: '/relatorios',
  pointsSimulator: {
    calculator: '/simulador',
    pdfGeneratorPage: '/pdfGeneratorPage',
    pdfGeneratorEmail: '/pdfGeneratorEmail',
  },
  qrCode: '/qr',
  receipts: '/extrato-notas',
};
