export default {
  font: {
    color: {
      primary: '#f4ede8',
      secondary: '#312e38',
      tertiary: '#fff',
    },
  },
  regulation: {
    primary: {
      backgroundColor: '#fff',
      scrollBarColor: '#c6c6c6',
      scrollBarBackgroundColor: '#312e38',
      fontColor: '#312e38',
      borderColor: '#312e38',
      openIconColor: '#193f4e',
      closeIconColor: '#d7d8da',
      backgroundOpenIconColor: '#d7d8da',
      backgroundCloseIconColor: '#193f4e',
    },
    secondary: {
      backgroundColor: '#fff',
      scrollBarColor: '#c6c6c6',
      scrollBarBackgroundColor: '#312e38',
      fontColor: '#312e38',
      borderColor: '#312e38',
      openIconColor: '#193f4e',
      closeIconColor: '#d7d8da',
      backgroundOpenIconColor: '#d7d8da',
      backgroundCloseIconColor: '#193f4e',
    },
  },
  menu: {
    activeBackgroundColor: '#f4ede8',
    inactiveBackgroundColor: '#fff',
  },
  contact: {
    ballon: {
      backgroundColor: '#c53030',
    },
  },
  modal: {
    primary: {
      backgroundColor: '#312e38',
      scrollBarColor: '#c6c6c6',
      scrollBarBackgroundColor: '#312e38',
    },
    secondary: {
      backgroundColor: '#312e38',
      scrollBarColor: '#c6c6c6',
      scrollBarBackgroundColor: '#312e38',
    },
  },
  input: {
    primary: {
      borderColor: '#232129',
      backgroundColor: '#232129',
      fontColor: '#f4ede8',
      iconColor: '#666360',
      placeholderColor: '#666360',
      errorIconColor: '#c53030',
      errorBorderColor: '#c53030',
      focusedBorderColor: '#ff9000',
      filledIconColor: '#ff9000',
      filledBorderColor: '#ff9000',
      labelFontColor: '#c53030',
      borderRadius: '10px',
      borderWidth: '2px',
      errorBorderWidth: '2px',
      focusedBorderWidth: '2px',
      filledBorderWidth: '2px',
      scrollBarColor: '#c6c6c6',
      scrollBarBackgroundColor: '#312e38',
    },
    secondary: {
      borderColor: '#232129',
      backgroundColor: '#232129',
      fontColor: '#f4ede8',
      iconColor: '#666360',
      placeholderColor: '#666360',
      errorIconColor: '#c53030',
      errorBorderColor: '#c53030',
      focusedBorderColor: '#ff9000',
      filledIconColor: '#ff9000',
      filledBorderColor: '#ff9000',
      labelFontColor: '#c53030',
      borderRadius: '10px',
      borderWidth: '2px',
      errorBorderWidth: '2px',
      focusedBorderWidth: '2px',
      filledBorderWidth: '2px',
      scrollBarColor: '#c6c6c6',
      scrollBarBackgroundColor: '#312e38',
    },
  },
  tooltip: {
    error: {
      borderColor: '#c53030',
      backgroundColor: '#c53030',
      fontColor: '#f4ede8',
    },
    success: {
      borderColor: '#00cc00',
      backgroundColor: '#00cc00',
      fontColor: '#312e38',
    },
    info: {
      borderColor: '#ff9000',
      backgroundColor: '#ff9000',
      fontColor: '#312e38',
    },
  },
  button: {
    primary: {
      backgroundColor: '#ff9000',
      fontColor: '#312e38',
      borderRadius: '10px',
    },
    secondary: {
      backgroundColor: '#ff9000',
      fontColor: '#312e38',
      borderRadius: '10px',
    },
  },
  link: {
    fontColor: '#f4ede8',
  },
};
