export const FETCH_BANNERS_ACTION = '@fmc/home/FETCH_BANNERS_ACTION';
export const FETCH_BANNERS_FAILURE = '@fmc/home/FETCH_BANNERS_FAILURE';
export const FETCH_BANNERS_SUCCESS = '@fmc/home/FETCH_BANNERS_SUCCESS';

export const FETCH_HIGHLIGHTS_ACTION = '@fmc/home/FETCH_HIGHLIGHTS_ACTION';
export const FETCH_HIGHLIGHTS_FAILURE = '@fmc/home/FETCH_HIGHLIGHTS_FAILURE';
export const FETCH_HIGHLIGHTS_SUCCESS = '@fmc/home/FETCH_HIGHLIGHTS_SUCCESS';

export const FETCH_SHOWCASEPRODUCTS_ACTION =
  '@fmc/home/FETCH_SHOWCASEPRODUCTS_ACTION';
export const FETCH_SHOWCASEPRODUCTS_FAILURE =
  '@fmc/home/FETCH_SHOWCASEPRODUCTS_FAILURE';
export const FETCH_SHOWCASEPRODUCTS_SUCCESS =
  '@fmc/home/FETCH_SHOWCASEPRODUCTS_SUCCESS';

export const FETCH_LUCKYNUMBER_ACTION = '@fmc/home/FETCH_LUCKYNUMBER_ACTION';
export const FETCH_LUCKYNUMBER_FAILURE = '@fmc/home/FETCH_LUCKYNUMBER_FAILURE';
export const FETCH_LUCKYNUMBER_SUCCESS = '@fmc/home/FETCH_LUCKYNUMBER_SUCCESS';

export enum HighlightTypes {
  Report = 'report',
  Quiz = 'quiz',
  FmcCampaign = 'fmc_campaign',
}
