export const FETCH_CAMPAIGNS_ACTION = '@fmc/goals/FETCH_CAMPAIGNS_ACTION';
export const FETCH_CAMPAIGNS_FAILURE = '@fmc/goals/FETCH_CAMPAIGNS_FAILURE';
export const FETCH_CAMPAIGNS_SUCCESS = '@fmc/goals/FETCH_CAMPAIGNS_SUCCESS';

export const FETCH_BILLING_POG_ACTION = '@fmc/goals/FETCH_BILLING_POG_ACTION';
export const FETCH_BILLING_POG_FAILURE = '@fmc/goals/FETCH_BILLING_POG_FAILURE';
export const FETCH_BILLING_POG_SUCCESS = '@fmc/goals/FETCH_BILLING_POG_SUCCESS';

export const FETCH_POTENTIALIZERS_ACTION =
  '@fmc/goals/FETCH_POTENTIALIZERS_ACTION';
export const FETCH_POTENTIALIZERS_FAILURE =
  '@fmc/goals/FETCH_POTENTIALIZERS_FAILURE';
export const FETCH_POTENTIALIZERS_SUCCESS =
  '@fmc/goals/FETCH_POTENTIALIZERS_SUCCESS';

export const FETCH_INFOS_ACTION = '@fmc/goals/FETCH_INFOS_ACTION';
export const FETCH_INFOS_FAILURE = '@fmc/goals/FETCH_INFOS_FAILURE';
export const FETCH_INFOS_SUCCESS = '@fmc/goals/FETCH_INFOS_SUCCESS';

export const FETCH_TOP_PURCHASING_PRODUCTS_ACTION =
  '@fmc/goals/FETCH_TOP_PURCHASING_PRODUCTS_ACTION';
export const FETCH_TOP_PURCHASING_PRODUCTS_FAILURE =
  '@fmc/goals/FETCH_TOP_PURCHASING_PRODUCTS_FAILURE';
export const FETCH_TOP_PURCHASING_PRODUCTS_SUCCESS =
  '@fmc/goals/FETCH_TOP_PURCHASING_PRODUCTS_SUCCESS';

export const FETCH_TOP_SELLING_PRODUCTS_ACTION =
  '@fmc/goals/FETCH_TOP_SELLING_PRODUCTS_ACTION';
export const FETCH_TOP_SELLING_PRODUCTS_FAILURE =
  '@fmc/goals/FETCH_TOP_SELLING_PRODUCTS_FAILURE';
export const FETCH_TOP_SELLING_PRODUCTS_SUCCESS =
  '@fmc/goals/FETCH_TOP_SELLING_PRODUCTS_SUCCESS';

export enum Tabs {
  Performance = 'performance',
  Top10Products = 'top-10-products',
}
